version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - revive
    - gosec
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
    gosec:
      excludes:
        - G304
        - G706

issues:
  exclude-dirs:
    - internal/db/sqlc
