server:
  port: 8080
  admin_password: "changeme"

exhibition:
  title: "Wildlife"
  subtitle: "Light - Dark"
  description: "Vote for your favourite photo!"

photos:
  - id: "photo1"
    title: "Sans Soucis"
    file: "dsc_4080_1.jpg"
  - id: "photo2"
    title: "Ping Pong"
    file: "dsc_4119.jpg"
    rotation: 270
  - id: "photo3"
    title: "Umbrella"
    file: "dsc_4095_1.jpg"
  - id: "photo4"
    title: "Walking Away"
    file: "dsc_4158.jpg"
    rotation: 270
