// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"time"
)

type DrawResult struct {
	ID      int64
	VoteID  int64
	DrawnAt time.Time
}

type Vote struct {
	ID        int64
	PhotoID   string
	SessionID string
	Name      string
	Email     string
	Phone     string
	CreatedAt time.Time
}
