// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: votes.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"time"
)

const castVote = `-- name: CastVote :one
INSERT INTO votes (photo_id, session_id, contact_token)
VALUES (?, ?, ?)
RETURNING id, photo_id, session_id, name, email, phone, contact_token, created_at
`

type CastVoteParams struct {
	PhotoID      string
	SessionID    string
	ContactToken string
}

func (q *Queries) CastVote(ctx context.Context, arg CastVoteParams) (Vote, error) {
	row := q.db.QueryRowContext(ctx, castVote, arg.PhotoID, arg.SessionID, arg.ContactToken)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.PhotoID,
		&i.SessionID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.ContactToken,
		&i.CreatedAt,
	)
	return i, err
}

const clearAllDrawResults = `-- name: ClearAllDrawResults :exec
DELETE FROM draw_results
`

func (q *Queries) ClearAllDrawResults(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearAllDrawResults)
	return err
}

const clearAllVotes = `-- name: ClearAllVotes :exec
DELETE FROM votes
`

func (q *Queries) ClearAllVotes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearAllVotes)
	return err
}

const getDrawResults = `-- name: GetDrawResults :many
SELECT dr.id, dr.vote_id, dr.drawn_at,
       v.photo_id, v.name, v.email
FROM draw_results dr
JOIN votes v ON v.id = dr.vote_id
ORDER BY dr.drawn_at DESC
`

type GetDrawResultsRow struct {
	ID      int64
	VoteID  int64
	DrawnAt time.Time
	PhotoID string
	Name    string
	Email   string
}

func (q *Queries) GetDrawResults(ctx context.Context) ([]GetDrawResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDrawResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDrawResultsRow
	for rows.Next() {
		var i GetDrawResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.VoteID,
			&i.DrawnAt,
			&i.PhotoID,
			&i.Name,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalVotes = `-- name: GetTotalVotes :one
SELECT COUNT(*) AS total FROM votes
`

func (q *Queries) GetTotalVotes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalVotes)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getVoteByID = `-- name: GetVoteByID :one
SELECT id, photo_id, session_id, name, email, phone, contact_token, created_at FROM votes WHERE id = ?
`

func (q *Queries) GetVoteByID(ctx context.Context, id int64) (Vote, error) {
	row := q.db.QueryRowContext(ctx, getVoteByID, id)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.PhotoID,
		&i.SessionID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.ContactToken,
		&i.CreatedAt,
	)
	return i, err
}

const getVoteBySession = `-- name: GetVoteBySession :one
SELECT id, photo_id, session_id, name, email, phone, contact_token, created_at FROM votes WHERE session_id = ?
`

func (q *Queries) GetVoteBySession(ctx context.Context, sessionID string) (Vote, error) {
	row := q.db.QueryRowContext(ctx, getVoteBySession, sessionID)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.PhotoID,
		&i.SessionID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.ContactToken,
		&i.CreatedAt,
	)
	return i, err
}

const getVoteCounts = `-- name: GetVoteCounts :many
SELECT photo_id, COUNT(*) AS vote_count
FROM votes
GROUP BY photo_id
`

type GetVoteCountsRow struct {
	PhotoID   string
	VoteCount int64
}

func (q *Queries) GetVoteCounts(ctx context.Context) ([]GetVoteCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getVoteCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVoteCountsRow
	for rows.Next() {
		var i GetVoteCountsRow
		if err := rows.Scan(&i.PhotoID, &i.VoteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVotersWithContact = `-- name: GetVotersWithContact :many
SELECT id, photo_id, session_id, name, email, phone, contact_token, created_at FROM votes
WHERE email != ''
`

func (q *Queries) GetVotersWithContact(ctx context.Context) ([]Vote, error) {
	rows, err := q.db.QueryContext(ctx, getVotersWithContact)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vote
	for rows.Next() {
		var i Vote
		if err := rows.Scan(
			&i.ID,
			&i.PhotoID,
			&i.SessionID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.ContactToken,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDrawResult = `-- name: RecordDrawResult :one
INSERT INTO draw_results (vote_id)
VALUES (?)
RETURNING id, vote_id, drawn_at
`

func (q *Queries) RecordDrawResult(ctx context.Context, voteID int64) (DrawResult, error) {
	row := q.db.QueryRowContext(ctx, recordDrawResult, voteID)
	var i DrawResult
	err := row.Scan(&i.ID, &i.VoteID, &i.DrawnAt)
	return i, err
}

const updateVoteContact = `-- name: UpdateVoteContact :execresult
UPDATE votes SET name = ?, email = ?
WHERE id = ? AND contact_token = ?
`

type UpdateVoteContactParams struct {
	Name         string
	Email        string
	ID           int64
	ContactToken string
}

func (q *Queries) UpdateVoteContact(ctx context.Context, arg UpdateVoteContactParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateVoteContact,
		arg.Name,
		arg.Email,
		arg.ID,
		arg.ContactToken,
	)
}
